import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { AGENCIES } from "./generators/agencies";
import { generateBudgetSpend } from "./generators/budgetSpend";
import { generateComplaints } from "./generators/complaints";
import { generateDailyMetrics } from "./generators/dailyMetrics";
import { REGIONS } from "./generators/regions";
import { generateServiceRequests } from "./generators/serviceRequests";
import { generateUtilityBilling } from "./generators/utilityBilling";
import { USERS } from "./generators/users";
import { buildInsertStatements, type SqlLiteral } from "./sqlWriter";

const __dirname = dirname(fileURLToPath(import.meta.url));

const REGION_ID_BY_CODE = new Map(REGIONS.map((r, i) => [r.code, i + 1]));
const AGENCY_ID_BY_CODE = new Map(AGENCIES.map((a, i) => [a.code, i + 1]));

function regionId(code: string): number {
  const id = REGION_ID_BY_CODE.get(code);
  if (!id) throw new Error(`Unknown region code: ${code}`);
  return id;
}

function agencyId(code: string): number {
  const id = AGENCY_ID_BY_CODE.get(code);
  if (!id) throw new Error(`Unknown agency code: ${code}`);
  return id;
}

function main(): void {
  const statements: string[] = [
    "-- Generated by apps/api/seed/seed.ts. Do not edit by hand; re-run the generator instead.",
    "PRAGMA defer_foreign_keys = TRUE;",
    "",
    "-- Reset (idempotent re-seed) --",
    "DELETE FROM narrative_cache;",
    "DELETE FROM audit_log;",
    "DELETE FROM anomaly_flags;",
    "DELETE FROM forecast_runs;",
    "DELETE FROM refresh_tokens;",
    "DELETE FROM budget_spend;",
    "DELETE FROM utility_consumption_monthly;",
    "DELETE FROM complaints;",
    "DELETE FROM daily_metrics;",
    "DELETE FROM service_requests;",
    "DELETE FROM users;",
    "DELETE FROM agencies;",
    "DELETE FROM regions;",
    "DELETE FROM sqlite_sequence WHERE name IN (" +
      "'regions','agencies','service_requests','daily_metrics','complaints'," +
      "'utility_consumption_monthly','budget_spend','forecast_runs','anomaly_flags'," +
      "'users','refresh_tokens','audit_log','narrative_cache');",
    "",
  ];

  // --- regions ---
  statements.push("-- regions --");
  statements.push(
    ...buildInsertStatements(
      "regions",
      ["code", "name_uz", "name_ru", "name_en", "population", "is_capital"],
      REGIONS.map(
        (r): SqlLiteral[] => [r.code, r.nameUz, r.nameRu, r.nameEn, r.population, r.isCapital]
      )
    )
  );

  // --- agencies ---
  statements.push("-- agencies --");
  statements.push(
    ...buildInsertStatements(
      "agencies",
      ["region_id", "code", "name_uz", "name_ru", "name_en", "sector", "org_type"],
      AGENCIES.map(
        (a): SqlLiteral[] => [
          a.regionCode ? regionId(a.regionCode) : null,
          a.code,
          a.nameUz,
          a.nameRu,
          a.nameEn,
          a.sector,
          a.orgType,
        ]
      )
    )
  );

  // --- users ---
  statements.push("-- users --");
  statements.push(
    ...buildInsertStatements(
      "users",
      ["external_id_hash", "full_name", "role", "region_id", "agency_id", "locale_pref"],
      USERS.map(
        (u): SqlLiteral[] => [
          u.externalIdHash,
          u.fullName,
          u.role,
          u.regionCode ? regionId(u.regionCode) : null,
          u.agencyCode ? agencyId(u.agencyCode) : null,
          u.localePref,
        ]
      )
    )
  );

  // --- daily_metrics ---
  const dailyMetrics = generateDailyMetrics(AGENCIES);
  statements.push(`-- daily_metrics (${dailyMetrics.length} rows) --`);
  statements.push(
    ...buildInsertStatements(
      "daily_metrics",
      ["agency_id", "region_id", "metric", "metric_date", "value"],
      dailyMetrics.map((row): SqlLiteral[] => {
        const agency = AGENCIES[AGENCY_ID_BY_CODE.get(row.agencyCode)! - 1]!;
        const regionCode = agency.regionCode;
        return [
          agencyId(row.agencyCode),
          regionCode ? regionId(regionCode) : nationalFallbackRegionId(),
          row.metric,
          row.date,
          row.value,
        ];
      })
    )
  );

  // --- service_requests ---
  const serviceRequests = generateServiceRequests(AGENCIES, REGIONS);
  statements.push(`-- service_requests (${serviceRequests.length} rows) --`);
  statements.push(
    ...buildInsertStatements(
      "service_requests",
      [
        "agency_id",
        "region_id",
        "category",
        "channel",
        "submitted_at",
        "resolved_at",
        "status",
        "processing_days",
        "citizen_age_bracket",
        "priority",
      ],
      serviceRequests.map(
        (row): SqlLiteral[] => [
          agencyId(row.agencyCode),
          regionId(row.regionCode),
          row.category,
          row.channel,
          row.submittedAt,
          row.resolvedAt,
          row.status,
          row.processingDays,
          row.citizenAgeBracket,
          row.priority,
        ]
      )
    )
  );

  // --- complaints ---
  const complaints = generateComplaints(AGENCIES);
  statements.push(`-- complaints (${complaints.length} rows) --`);
  statements.push(
    ...buildInsertStatements(
      "complaints",
      ["agency_id", "region_id", "category", "severity", "submitted_at", "resolved_at", "sentiment_score"],
      complaints.map((row): SqlLiteral[] => {
        const agency = AGENCIES[AGENCY_ID_BY_CODE.get(row.agencyCode)! - 1]!;
        const regionCode = agency.regionCode;
        return [
          agencyId(row.agencyCode),
          regionCode ? regionId(regionCode) : nationalFallbackRegionId(),
          row.category,
          row.severity,
          row.submittedAt,
          row.resolvedAt,
          row.sentimentScore,
        ];
      })
    )
  );

  // --- utility_consumption_monthly ---
  const utilityBilling = generateUtilityBilling(AGENCIES);
  statements.push(`-- utility_consumption_monthly (${utilityBilling.length} rows) --`);
  statements.push(
    ...buildInsertStatements(
      "utility_consumption_monthly",
      [
        "agency_id",
        "region_id",
        "year_month",
        "service_type",
        "consumption_units",
        "billed_amount",
        "collected_amount",
        "arrears_amount",
        "meter_count",
      ],
      utilityBilling.map((row): SqlLiteral[] => {
        const agency = AGENCIES[AGENCY_ID_BY_CODE.get(row.agencyCode)! - 1]!;
        return [
          agencyId(row.agencyCode),
          regionId(agency.regionCode!),
          row.yearMonth,
          row.serviceType,
          row.consumptionUnits,
          row.billedAmount,
          row.collectedAmount,
          row.arrearsAmount,
          row.meterCount,
        ];
      })
    )
  );

  // --- budget_spend ---
  const budgetSpend = generateBudgetSpend(AGENCIES);
  statements.push(`-- budget_spend (${budgetSpend.length} rows) --`);
  statements.push(
    ...buildInsertStatements(
      "budget_spend",
      ["agency_id", "region_id", "year", "quarter", "category", "planned_amount", "actual_amount"],
      budgetSpend.map((row): SqlLiteral[] => {
        const agency = AGENCIES[AGENCY_ID_BY_CODE.get(row.agencyCode)! - 1]!;
        return [
          agencyId(row.agencyCode),
          agency.regionCode ? regionId(agency.regionCode) : null,
          row.year,
          row.quarter,
          row.category,
          row.plannedAmount,
          row.actualAmount,
        ];
      })
    )
  );

  const outDir = join(__dirname, "output");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "seed.sql");
  writeFileSync(outPath, statements.join("\n") + "\n", "utf-8");

  // eslint-disable-next-line no-console
  console.log(`Wrote ${outPath}`);
  console.log(`  regions: ${REGIONS.length}, agencies: ${AGENCIES.length}, users: ${USERS.length}`);
  console.log(`  daily_metrics: ${dailyMetrics.length}, service_requests: ${serviceRequests.length}`);
  console.log(`  complaints: ${complaints.length}, utility_consumption_monthly: ${utilityBilling.length}`);
  console.log(`  budget_spend: ${budgetSpend.length}`);
}

// National ministries have no home region; their daily_metrics/complaints rows are
// attributed to the capital for aggregation purposes (the metric itself is
// agency-scoped, region_id here is descriptive, not authoritative).
function nationalFallbackRegionId(): number {
  return regionId("TSH");
}

main();
